//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anteater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SocketTimeoutException</string>
  <string>KeepAlive</string>
  <string>MLAPI</string>
  <string>JSON</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection messageTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["messageTypes"]));
            }
            set {
                this["messageTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Connecting</string>
  <string>connecting</string>
  <string>Connected</string>
  <string>connected</string>
  <string>Created</string>
  <string>created</string>
  <string>Creating</string>
  <string>creating</string>
  <string>Destroying</string>
  <string>destroying</string>
  <string>Destroyed</string>
  <string>destroyed</string>
  <string>Error</string>
  <string>error</string>
  <string>Exception</string>
  <string>exception</string>
  <string>Exist</string>
  <string>exist</string>
  <string>Exit</string>
  <string>exit</string>
  <string>Failed</string>
  <string>failed</string>
  <string>Initialized</string>
  <string>initialized</string>
  <string>Initializing</string>
  <string>initializing</string>
  <string>Network</string>
  <string>network</string>
  <string>Remove</string>
  <string>remove</string>
  <string>Removed</string>
  <string>removed</string>
  <string>Removing</string>
  <string>removing</string>
  <string>Stopping</string>
  <string>stopping</string>
  <string>Timed</string>
  <string>timed</string>
  <string>Trying</string>
  <string>trying</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection interestingStrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["interestingStrings"]));
            }
            set {
                this["interestingStrings"] = value;
            }
        }
    }
}
